#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "sas2yaml"
require "sas2yaml/assemble_command"
require "optparse"

options = {}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: sas2yaml [options] FILE..."
  opts.separator ""
  opts.separator Sas2Yaml::DESCRIPTION
  opts.separator ""
  opts.separator "Options:"

  opts.on("--verbose", "Enable verbose/debug output") do
    options[:verbose] = true
  end

  opts.on("-v", "--version", "Print version") do
    puts "sas2yaml #{Sas2Yaml::VERSION}"
    exit
  end

  opts.on("-h", "--help", "Print this help") do
    puts opts
    exit
  end
end

parser.parse!

if ARGV.empty?
  warn "Error: No input files specified"
  warn parser
  exit 1
end

Sas2Yaml.verbose! if options[:verbose]

Sas2Yaml::AssembleCommand.new(ARGV).execute
