#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "sas2yaml"
require "sas2yaml/assemble_command"

Escort::App.create do |app|
  app.version Sas2Yaml::VERSION
  app.summary Sas2Yaml::SUMMARY
  app.description Sas2Yaml::DESCRIPTION

  app.action do |options, arguments|
    Sas2Yaml::AssembleCommand.new(options, arguments).execute
  rescue StandardError => e
    warn e.message
    warn e.backtrace.join("\n")
    raise
  end
end
